apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: python-k8s-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
