apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: python-project
  namespace: argocd
spec:
  description: Project for Python App deployments
  sourceRepos:
    - 'https://github.com/yourusername/my-python-app-repo.git'
  destinations:
    - namespace: default
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
